[package]
name = "mio-ob"
version = "0.1.0"
edition = "2021"

[dependencies]
screenshots = { version = "0.7.2", optional = true }
clipboard-master = { version = "3.1.3", optional = true }

[features]
default = ["screenshots", "clipboard"]
clipboard = ["clipboard-master"]
